#!/bin/sh

mkdir -p opk
cp ./game.elf opk/game.elf
cp icon.png opk/icon.png
cp -r assets/ opk/
# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Your Gayme
Comment=A gay porn game
Exec=game.elf
Icon=icon
Terminal=false
Type=Application
Categories=games;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk game_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
